loki:
  resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 25m # default 100m
    memory: 128Mi

promtail:
  resources: 
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 25m # default 100m
      memory: 128Mi