persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
    
logstashPipeline:
  uptime.conf: |
    filter {
      json {
        source => "message"
      }
    }
    
    output { 
      elasticsearch { hosts => ["http://elasticsearch-master:9200"] } 
    }

resources:
  requests:
    cpu: 100m # default 100m
    memory: 500Mi # default 1536Mi
  limits:
    cpu: 600m # default 1000m
    memory: 1536Mi # default 1536Mi
