loki:
  resources: 
    requests:
      cpu: 25m # default 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

promtail:
  resources: 
    requests:
      cpu: 25m # default 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi
